[project]
dependencies = [
  "lightning>=2.5.1.post0",
  "mosaicml-streaming>=0.12.0",
  "torch>=2.7.0",
  "torchvision>=0.22.0",
]
description = "Add your description here"
name = "mosaicml-streaming-torchrun"
readme = "README.md"
requires-python = ">=3.11,<3.12"
version = "0.1.0"
